#pragma once

#define NO_ARGS "Function expects no arguments"
#define ONE_ARG "Function expects one argument"
#define TWO_ARGS "Function expects two arguments"
#define ARITH_NUMERIC "Arithmetic operation expects two numeric values"
#define MODULO_INT "Modulo expects two integers"
#define FORM_INADEQUATE_ARGS "Too few arguments to expression"
#define FORM_SUPERFLOUS_ARGS "Too many arguments to expression"
#define MALFORMED_SYNTAX "Malformed syntax declaration"
#define MALFORMED_LAMBDA "Malformed lambda declaration"
#define MALFORMED_CATCH "Malformed catch expression"
#define PAIR_ARG "Function expects a pair argument"
#define FLOAT_ARG "Function expects a float argument"
#define ALLOC_FAIL "Host memory allocation failed"
#define READ_ERROR "Read error"
#define EXC_TYPE_ERROR "Value is not an exception"
#define INT_REQUIRED "Integer argument required"
#define OUT_OF_RANGE "Argument out of range"
#define CANT_CONVERT "Unable to convert argument type"

