#pragma once

#define NO_ARGS "Function expects no arguments"
#define ONE_ARG "Function expects one argument"
#define TWO_ARGS "Function expects two arguments"
#define ARITH_NUMERIC "Arithmetic operation expects two numeric values"
#define MODULO_INT "Modulo expects two integers"
#define FORM_INADEQUATE_ARGS "Too few arguments to expression"
#define FORM_SUPERFLOUS_ARGS "Too many arguments to expression"
#define MALFORMED_SYNTAX "Malformed syntax declaration"
#define MALFORMED_LAMBDA "Malformed lambda declaration"
#define MALFORMED_CATCH "Malformed catch expression"
#define PAIR_ARG "Function expects a pair argument"
#define FLOAT_ARG "Function expects a float argument"
#define ALLOC_FAIL "Host memory allocation failed"
#define READ_ERROR "Read error"
#define WRITE_ERROR "Write error"
#define EXC_TYPE_ERROR "Value is not an exception"
#define INT_REQUIRED "Integer argument required"
#define OUT_OF_RANGE "Argument out of range"
#define CANT_CONVERT "Unable to convert argument type"
#define STRING_REQUIRED "String argument required"
#define FILE_OPEN_FAILED "Failed to open file"
#define PORT_REQUIRED "Port argument required"
#define UNTERMINATED_EXPRESSION "Unterminated expression"
#define BOOL_REQUIRED "Bool argument required"
#define PARSE_ERROR "Failed to parse expression"
#define INVALID_MODE "Invalid file mode"
#define EXPECTED_HANDLE "File handle argument expected"
#define END_OF_FILE "End of file"
#define SYMBOL_REQUIRED "Symbol argument required"
#define PROC_EXPECTED "Procedure argument required"

